[workspace]
members = [
    "lib",
    "program",
    "script",
    "api",
]
resolver = "2"

[workspace.dependencies]
axum = { version = "0.7.4", features = ["multipart", "json"] }
sp1-sdk = "4.0.0"
alloy-sol-types = "0.6"
serde = "1.0"
serde_json = "1.0"
rubato = "0.15.0"
hound = "3.4.0"