[package]
name = "zk-sampler-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "4.0.0"
sha3 = "0.10.8"
hex = "0.4.3"
zk-sampler-lib = { path = "../lib" }
alloy-sol-types = { workspace = true }
k256 = "0.13"